[ ;;principio de la lista de ejemplos
 [ ;;definicion de los atributos
  [:perspectiva [:soleado :niebla :nublado :lluvioso :diluvia]]
  [:temperatura :numerico]
  [:humedad :numerico]
  [:viento [:no :si]]
  [:animo [:contento :normal :triste]]
  [:estres [:relajado :normal :estresado]]
  [:dinero [:solvente :ajustado :insuficiente]]
  [:clase [:+ :-]]] ;;fin definicion de atributos
 ;;Ejemplos
 [:nublado 20 90 :si :contento :relajado :ajustado :- ]
 [:soleado 25 86 :no :contento :relajado :solvente :+ ]
 [:lluvioso 30 70 :no :normal :normal :insuficiente :- ]
 [:niebla 28 80 :no :contento :estresado :solvente :+ ]
 [:diluvia 35 75 :no :normal :relajado :ajustado :- ]
 [:nublado 22 84 :no :triste :normal :solvente :- ]
 [:soleado 37 95 :si :normal :estresado :solvente :- ]
 [:lluvioso 31 82 :no :contento :relajado :solvente :+ ]
 [:niebla 26 78 :no :triste :estresado :insuficiente :- ]
 [:diluvia 27 79 :no :contento :normal :solvente :- ]
 [:nublado 32 92 :si :contento :relajado :ajustado :- ]
 [:soleado 24 86 :no :normal :relajado :insuficiente :+ ]
 [:lluvioso 18 81 :no :triste :estresado :insuficiente :- ]
 [:niebla 15 70 :no :contento :relajado :solvente :+ ]
 [:diluvia 20 70 :si :normal :estresado :insuficiente :- ]
 [:nublado 16 65 :no :contento :relajado :solvente :- ]
 [:soleado 30 90 :no :contento :normal :solvente :+ ]
 [:lluvioso 40 92 :no :triste :estresado :ajustado :- ]
 [:niebla 28 88 :no :normal :normal :solvente :+ ]
 [:diluvia 29 80 :si :contento :normal :ajustado :- ]]
