[ ;;principio de la lista de ejemplos
 [ ;;definicion de los atributos
  [:perspectiva [:nublado :soleado :lluvioso :niebla :diluvia]]
  [:temperatura :numerico]
  [:humedad :numerico]
  [:viento [:fuerte :brisa :no]]
  [:animo [:contento :normal :triste]]
  [:estres [:relajado :normal :estresado]]
  [:dinero [:solvente :ajustado :insuficiente]]
  [:clase [:+ :-]]] ;;fin definicion de atributos
 ;;Ejemplos
 [:nublado 20 90 :fuerte :contento :relajado :ajustado :- ]
 [:soleado 25 86 :brisa :contento :relajado :solvente :+ ]
 [:lluvioso 30 70 :brisa :normal :normal :insuficiente :- ]
 [:niebla 28 80 :no :contento :estresado :solvente :+ ]
 [:diluvia 35 75 :no :normal :relajado :ajustado :- ]
 [:nublado 22 84 :brisa :triste :normal :solvente :- ]
 [:soleado 37 95 :fuerte :normal :estresado :solvente :- ]
 [:lluvioso 31 82 :brisa :contento :relajado :solvente :+ ]
 [:niebla 26 78 :no :triste :estresado :insuficiente :- ]
 [:diluvia 27 79 :brisa :contento :normal :solvente :- ]
 [:nublado 32 92 :fuerte :contento :relajado :ajustado :- ]
 [:soleado 24 86 :brisa :normal :relajado :insuficiente :+ ]
 [:lluvioso 18 81 :brisa :triste :estresado :insuficiente :- ]
 [:niebla 15 70 :no :contento :relajado :solvente :+ ]
 [:diluvia 20 70 :fuerte :normal :estresado :insuficiente :- ]
 [:nublado 16 65 :brisa :contento :relajado :solvente :- ]
 [:soleado 30 90 :no :contento :normal :solvente :+ ]
 [:lluvioso 40 92 :brisa :triste :estresado :ajustado :- ]
 [:niebla 28 88 :brisa :normal :normal :solvente :+ ]
 [:diluvia 29 80 :fuerte :contento :normal :ajustado :- ]]
