[;;principio de la lista de ejemplos
 [;;definicion de los atributos
  [perspectiva [soleado nublado lluvioso]]
  [temperatura numerico]
  [humedad numerico]
  [viento [no si]]
  [animo [contento triste]]
  [estres [relajado estresado]]
  [dinero [solvente insuficiente]]
  [clase [++ --]]] ;;fin definicion de atributos
 ;;Ejemplos
 [nublado 15 90 si contento relajado insuficiente --]
 [soleado 25 86 no contento relajado solvente ++]
 [lluvioso 30 70 no triste relajado insuficiente --]
 [nublado 28 80 no contento estresado solvente ++]
 [lluvioso 35 75 no contento estresado insuficiente --]
 [nublado 22 84 no triste relajado solvente --]
 [soleado 37 95 si triste estresado solvente --]
 [lluvioso 31 82 no contento relajado solvente ++]
 [nublado 26 78 no triste estresado insuficiente --]
 [lluvioso 27 79 si contento relajado insuficiente --]
 [nublado 32 92 si contento relajado solvente ++]
 [soleado 24 86 no contento relajado insuficiente ++]
 [lluvioso 18 81 no triste estresado insuficiente --]
 [nublado 15 70 no contento relajado solvente ++]
 [lluvioso 20 70 si contento estresado insuficiente --]
 [nublado 6 65 no contento relajado solvente --]
 [soleado 30 90 no contento estresado solvente ++]
 [lluvioso 40 92 no triste estresado insuficiente --]
 [nublado 28 88 no contento relajado solvente ++]
 [lluvioso 29 80 si contento relajado solvente ++]]
