(ns amanas17.maia.symbols)

(def perspectiva 'perspectiva)
(def soleado 'soleado)
(def nublado 'nublado)
(def lluvioso 'lluvioso)
(def temperatura 'temperatura)
(def numerico 'numerico)
(def humedad 'humedad)
(def viento 'viento)
(def no 'no)
(def si 'si)
(def animo 'animo)
(def contento 'contento)
(def triste 'triste)
(def estres 'estres)
(def relajado 'relajado)
(def estresado 'estresado)
(def dinero 'dinero)
(def solvente 'solvente)
(def insuficiente 'insuficiente)
(def clase 'clase)
;; TODO: replace ** by '* everywhere
(def ** '**)
(def +inf '+inf)
(def -inf '-inf)
;; ;; (def ++ '++)
;; ;; (def -- '--)
;; (def a 'a)
;; (def b 'b)
;; (def c 'c)
;; (def d 'd)
;; (def e 'e)
;; (def f 'f)
;; (def g 'g)
;; (def h 'h)
;; (def i 'i)
;; (def j 'j)
;; (def k 'k)
;; (def l 'l)
;; (def m 'm)
;; (def n 'n)
;; (def o 'o)
;; (def p 'p)
;; (def q 'q)
;; (def r 'r)
;; (def s 's)
;; (def t 't)
;; (def u 'u)
;; (def v 'v)
;; (def w 'w)
;; (def x 'x)
;; (def y 'y)
;; (def z 'z)
;; (def cap-shape   'cap-shape  )
;; (def cap-surface  'cap-surface )
;; (def cap-color   'cap-color  )
;; (def bruises?   'bruises?  )
;; (def odor   'odor  )
;; (def gill-attachment   'gill-attachment  )
;; (def gill-spacing   'gill-spacing  )
;; (def gill-size   'gill-size  )
;; (def gill-color   'gill-color  )
;; (def stalk-shape   'stalk-shape  )
;; (def stalk-root   'stalk-root  )
;; (def stalk-surface-above-ring   'stalk-surface-above-ring  )
;; (def stalk-surface-below-ring   'stalk-surface-below-ring  )
;; (def stalk-color-above-ring   'stalk-color-above-ring  )
;; (def stalk-color-below-ring   'stalk-color-below-ring  )
;; (def veil-type   'veil-type  )
;; (def veil-color   'veil-color  )
;; (def ring-number   'ring-number  )
;; (def ring-type   'ring-type  )
;; (def spore-print-color   'spore-print-color  )
;; (def population   'population  )
;; (def habitat 'habitat)
