(ns amanas17.maia.symbols)

(def perspectiva 'perspectiva)
(def soleado 'soleado)
(def nublado 'nublado)
(def lluvioso 'lluvioso)
(def temperatura 'temperatura)
(def numerico 'numerico)
(def humedad 'humedad)
(def viento 'viento)
(def no 'no)
(def si 'si)
(def animo 'animo)
(def contento 'contento)
(def triste 'triste)
(def estres 'estres)
(def relajado 'relajado)
(def estresado 'estresado)
(def dinero 'dinero)
(def solvente 'solvente)
(def insuficiente 'insuficiente)
(def clase 'clase)
(def ++ '++)
(def -- '--)
(def ** '**)
(def +inf '+inf)
(def -inf '-inf)
